language: python
python:
    - 2.7
    - 3.4
env:
    secure: ZWyoyE+8qgGjZtbUp0w6AgOLix2odsNUOpsT6NqTA9DyulBufTZo43UtYHUa26sX5b26+GqgV+Dvkh3CGERhaoIdUE3j9Nb3LBNXvml52Q50kkMWdjmxGHqzB7lzX7Rsf2N3R8YRJaku7RMSCc5cgvF140xQuzBwYXNmkvxTuT15xRS3SwSeiQR8iaEv8SEEZbdCVyBcM2ew3qM45/hWYCJRSVlKCrQFfYTq8NZJEAFNJOZuU5OgMcEJBaNHwhutb71joQlSYhqSbuWr1vJpVLGz/Ky6urhqQbDpQZ2Cdeyr48B7E7uLE1rza1QREskQjwrU/36hx9EzSqqoihLtgA==
before_install:
    - pip install pep8
install:
    - pip install . --use-mirrors
    - chmod +x tests/test-cli.sh
script:
    - python setup.py nosetests --with-cov --cover-package=decipher
    - ./tests/test-cli.sh
    - pep8 --ignore=E501 decipher/
    - pep8 --ignore=E501 tests/
notifications:
    email: false
after_success:
    - export PYTHON_VERSION=`python -c "import sys; print(sys.version.split(',')[0])" | awk -F' ' '{print $1}'`
    - export HIPCHAT="https://api.hipchat.com/v1/rooms/message?auth_token=${HIPCHAT_TOKEN}&format=json"
    - export SHORT=`echo $COMMIT | cut -c 1-10`
    - export HC_PREFIX="room_id=642430&from=Shippable&message=Decipher#${BUILD_NUMBER}+(${BRANCH}:${SHORT}:python=${PYTHON_VERSION})"
    - curl -d "${HC_PREFIX}+build+passed&color=green" $HIPCHAT
after_failure:
    - export PYTHON_VERSION=`python -c "import sys; print(sys.version.split(',')[0])" | awk -F' ' '{print $1}'`
    - export HIPCHAT="https://api.hipchat.com/v1/rooms/message?auth_token=${HIPCHAT_TOKEN}&format=json"
    - export SHORT=`echo $COMMIT | cut -c 1-10`
    - export HC_PREFIX="room_id=642430&from=Shippable&message=Decipher#${BUILD_NUMBER}+(${BRANCH}:${SHORT}:python=${PYTHON_VERSION})"
    - curl -d "${HC_PREFIX}+build+passed&color=green" $HIPCHAT
